### ISSUE TITLE
failed to  parsing .diag file if it is has "[]" in label description

### ISSUE THREAD

**Issue by monstercy** [Nudin/iptable_vis#10]
Thank you very much for your wonderfull tool. it helps a lot when using it. I occur a issue that when parsing the diag file . could you kindly take a look?

Chain ufw-user-limit (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 LOG        all  --  any    any     anywhere             anywhere             limit: avg 3/min burst 5 LOG level warning prefix "[UFW LIMIT BLOCK] "
    0     0 REJECT     all  --  any    any     anywhere             anywhere             reject-with icmp-port-unreachable

**Comment by alan-wint** [comment]
Same issue with `()` and `<>` unfortunately

**Comment by Gustav74** [comment]
@Nudin, @monstercy 

I had the same problem also coming from UFW analysis.

It seem to come from the double quoting of code in line 71
`print indent target_node_name " [class=reject, label=\"" target_label "\"]"`

must be replaced by:
`print indent target_node_name " [class=reject, label='" target_label "']"`

so I replaced all `\"` by `'`
diff (lines 183,189c183,189 are more fine-tuning):

```diff
71c71
< 	print indent name " [class=rule, label='" label "']"
---
> 	print indent name " [class=rule, label=\"" label "\"]"
157c157
< 			print indent target_node_name " [class=reject, label='" target_label "']"
---
> 			print indent target_node_name " [class=reject, label=\"" target_label "\"]"
163c163
< 			print indent target_node_name " [class=target, class='" target_label "', label='" target_label "']"
---
> 			print indent target_node_name " [class=target, class=\"" target_label "\", label=\"" target_label "\"]"
183,189c183,189
< 	print indent "class reject [color = 'red', label='REJECT']"
< 	print indent "class reject_line [color = 'red']"
< 	print indent "class drop [color = 'red', label='DROP']"
< 	print indent "class return [color = '#1ab3ff', label='RETURN']"
< 	print indent "class return_line [color = 'blue']"
< 	print indent "class accept [color = 'lightgreen', label='ACCEPT']"
< 	print indent "class accept_line [color = 'green']"
---
> 	print indent "class reject [color = \"red\", label=\"REJECT\"]"
> 	print indent "class reject_line [color = \"red\"]"
> 	print indent "class drop [color = \"red\", label=\"DROP\"]"
> 	print indent "class return [color = \"#1ab3ff\", label=\"RETURN\"]"
> 	print indent "class return_line [color = \"blue\"]"
> 	print indent "class accept [color = \"lightgreen\", label=\"ACCEPT\"]"
> 	print indent "class accept_line [color = \"green\"]"
199c199
< 			style="shape=ellipse, style=dotted, linecolor='#444', textcolor='#444'"
---
> 			style="shape=ellipse, style=dotted, linecolor=\"#444\", textcolor=\"#444\""
```
