### ISSUE TITLE
Quotation marks in rules result in broken diag code.

### ISSUE THREAD

**Issue by Nudin** [Nudin/iptable_vis#2]

**Comment by autostatic** [comment]
Maybe change the escaped double quotes in line 71 to single quotes.
```
diff --git a/iptables-vis.awk b/iptables-vis.awk
index 709bcf0..0028e5d 100755
--- a/iptables-vis.awk
+++ b/iptables-vis.awk
@@ -68,7 +68,7 @@ in_chain && /^ *[0-9]/ {
                label = "*"
        gsub(/  /, " ", label);
        gsub(/^ *| *$/, "", label);
-       print indent name " [class=rule, label=\"" label "\"]"
+       print indent name " [class=rule, label='" label "']"
        print indent last, "->", name
        last=name
        filter_nodes[num_targets++] = name
```

**Comment by Gustav74** [comment]
See also #10

**Comment by Nudin** [comment]
Yes, this is an easy fix for these cases. But I suspect that it will result in broken code if the label contains an `'` – so probably one might do a search-and-replace to escape those?

Still, changing to single quotes fixes the problem for all ufw users – probably much more than users that have a single quote in their rules.
