### ISSUE TITLE
Blockdiag doesn't seem available.

### ISSUE THREAD

**Issue by griloHBG** [Nudin/iptable_vis#9]
On Ubuntu 21.04, `blockdiag` doesn't seem available:

```
sudo apt install blockdiag
[sudo] password for user:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package blockdiag
```

Using `python3-blockdiag` instead seems good.

```
sudo apt install python3-blockdiag
blockdiag3 iptables.dia -T svg -o iptables.svg
```

And the image was rendered.

Btw, nice tool! :D

**Comment by Nudin** [comment]
Yes, depending on distribution and/or package manager the name varies. I linked the project so it's clear what program is needed.
